server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/healthcare/bulgaria/doctors/**, /api/healthcare/bulgaria/specialties/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/healthcare/bulgaria/patients/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/healthcare/bulgaria/appointments/**, /api/healthcare/bulgaria/diagnoses/**, /api/healthcare/bulgaria/pricing/**
        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/healthcare/bulgaria/stats/**
